### ISSUE TITLE
Keygaen not runnable without a web server

### ISSUE THREAD

**Issue by flavienbwk** [pojntfx/gridge#2]
Hi,

This repo provides a compiled version of Keygaen to be hosted on a CDN (in Release).
However, I try to run the index.html file in my browser from a local directory and get some errors in the browser.

![image](https://github.com/pojntfx/keygaen/assets/14158127/e14548cc-8edc-4c09-adaf-e3a1690438b0)

How to make Keygaen work from a local directory?

Thank you,

**Comment by flavienbwk** [comment]
To be confirmed but it looks like this project can't be run through local files [due to serviceworkers only working with the HTTP protocol](https://stackoverflow.com/questions/44564888/service-worker-with-file-origin-doesnt-work).

Another local solution might be to use the `http.server` module from Python 3 : 

```bash
# inside the keygaen pwa directory
python3 -m http.server
```

**Comment by pojntfx** [comment]
No need to do that! Keygaen is a PWA, so it works offline once you've visited it once! Just head over to https://pojntfx.github.io/keygaen/, and in the top right hand corner using any Chromium-based browser, click on the "Install app" button, and it will work offline :)

![image](https://github.com/pojntfx/keygaen/assets/28832235/b846bf27-9fad-4ab3-9bf8-67de3891bde4)

**Comment by flavienbwk** [comment]
Hi pojntfx! Thank you but I don't have access to "https://pojntfx.github.io/keygaen/" where I want to use it. I want to be able running it from local files. Which looks unfeasible with the current architecture. I close this issue as it can't be easily answered.
